[tool.poetry]
name = "django-lightweight-queue"
version = "0.1.0"
description = "Lightweight & modular queue and cron system for Django"
authors = ["Thread Engineering <tech@thread.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.5"
django = ">=1.11.27,<3.0"
daemonize = "^2.5.0"
redis = "^3.3.11"
prometheus-client = "^0.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
