version: 2.1

references:
  install-poetry: &install-poetry
    run:
      name: Install Poetry
      command: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  restore-dependencies-cache: &restore-dependencies-cache
    restore_cache:
      keys:
        - deps-py<< parameters.version >>-{{ checksum "poetry.lock" }}
  install-dependencies: &install-dependencies
    run:
      name: Install Dependencies
      command: |
        source $HOME/.poetry/env
        poetry install
  save-dependencies-cache: &save-dependencies-cache
    save_cache:
      key: deps-py<< parameters.version >>-{{ checksum "poetry.lock" }}
      paths:
        - /home/circleci/.cache/pypoetry/virtualenvs
  parametrised-python-executor: &parametrised-python-executor
    parameters:
      version:
        type: string
    executor:
      name: python
      version: << parameters.version >>
  python-version-matrix: &python-version-matrix
    matrix:
      parameters:
        version: ["3.5.5", "3.6", "3.7", "3.8"]

executors:
  python:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/python:<< parameters.version >>

jobs:
  build-test:
    <<: *parametrised-python-executor

    steps:
      - checkout

      - *install-poetry
      - *restore-dependencies-cache
      - *install-dependencies
      - *save-dependencies-cache

      - run:
          name: Run Tests
          command: |
            source $HOME/.poetry/env
            poetry run ./runtests

  lint:
    <<: *parametrised-python-executor

    steps:
      - checkout

      - *install-poetry
      - *restore-dependencies-cache
      - *install-dependencies
      - *save-dependencies-cache

      - run:
          name: Run Flake8
          command: |
            source $HOME/.poetry/env
            poetry run flake8

  type-check:
    <<: *parametrised-python-executor

    steps:
      - checkout

      - *install-poetry
      - *restore-dependencies-cache
      - *install-dependencies
      - *save-dependencies-cache

      - run:
          name: Run Mypy
          command: |
            source $HOME/.poetry/env
            poetry run ./script/type-check

  deploy:
    executor:
      name: python
      version: "3.5.5"
    steps:
      - checkout
      - run:
          name: Push to PyPI
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            source $HOME/.poetry/env
            poetry publish \
              --build \
              --username "${PYPI_USERNAME}" \
              --password "${PYPI_PASSWORD}" \
              --no-interaction

workflows:
  version: 2.1

  build-test:
    jobs:
      - build-test:
          <<: *python-version-matrix
      - lint:
          <<: *python-version-matrix
      - type-check:
          <<: *python-version-matrix


  build-test-deploy:
    jobs:
      - build-test:
          <<: *python-version-matrix
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      - lint:
          <<: *python-version-matrix
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      - type-check:
          <<: *python-version-matrix
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      - deploy:
          context: thread-pypi
          requires:
            - build-test
            - lint
            - type-check
          filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/
